In [262]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [263]:
train = pd.read_csv('/content/train.csv')

In [264]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [265]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [266]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [267]:
train.shape

(891, 12)

In [268]:
train = train.drop(columns='Cabin', axis = 1)
train = train.drop(columns='Name', axis = 1)

In [269]:
train = train.drop(columns= 'Embarked', axis = 1)

In [270]:
train = train.drop(columns= 'Ticket', axis = 1)

In [271]:
train['Fare'] = train['Fare']/513

In [272]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [273]:
train.tail()

     PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch      Fare
886          887         0       2    male  27.0      0      0  0.025341
887          888         1       1  female  19.0      0      0  0.058480
888          889         0       3  female   NaN      1      2  0.045712
889          890         1       1    male  26.0      0      0  0.058480
890          891         0       3    male  32.0      0      0  0.015107

In [274]:
train['Sex'].replace({'male': 1 }, inplace = True)

In [275]:
train['Sex'].replace({'female': 0 }, inplace = True)

In [276]:
train.head()

   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch      Fare
0            1         0       3    1  22.0      1      0  0.014133
1            2         1       1    0  38.0      1      0  0.138954
2            3         1       3    0  26.0      0      0  0.015448
3            4         1       1    0  35.0      1      0  0.103509
4            5         0       3    1  35.0      0      0  0.015692

In [277]:
train_without_missing = train.dropna()

In [278]:
train_without_missing.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
dtype: int64

In [279]:
train_without_missing.shape

(714, 8)

In [280]:
X = train_without_missing.drop('Survived', axis =1)

In [281]:
Y = train_without_missing['Survived']

In [282]:
X.head()

   PassengerId  Pclass  Sex   Age  SibSp  Parch      Fare
0            1       3    1  22.0      1      0  0.014133
1            2       1    0  38.0      1      0  0.138954
2            3       3    0  26.0      0      0  0.015448
3            4       1    0  35.0      1      0  0.103509
4            5       3    1  35.0      0      0  0.015692

In [283]:
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [284]:
Y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [285]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 2, stratify = Y)

In [286]:
X_train.shape

(571, 7)

In [287]:
X_test.shape

(143, 7)

In [288]:
classifier = LogisticRegression()

In [289]:
train.corr()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
PassengerId,1.000000,-0.005007,-0.035144,0.042939,0.036847,-0.057527,-0.001652,0.012658
Survived,-0.005007,1.000000,-0.338481,-0.543351,-0.077221,-0.035322,0.081629,0.257307
Pclass,-0.035144,-0.338481,1.000000,0.131900,-0.369226,0.083081,0.018443,-0.549500
Sex,0.042939,-0.543351,0.131900,1.000000,0.093254,-0.114631,-0.245489,-0.182333
Age,0.036847,-0.077221,-0.369226,0.093254,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.057527,-0.035322,0.083081,-0.114631,-0.308247,1.000000,0.414838,0.159651
Parch,-0.001652,0.081629,0.018443,-0.245489,-0.189119,0.414838,1.000000,0.216225
Fare,0.012658,0.257307,-0.549500,-0.182333,0.096067,0.159651,0.216225,1.000000

In [290]:
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [307]:
Y_train_pred = classifier.predict(X_train)

In [308]:
accuracy_train = accuracy_score(Y_train_pred, Y_train)

In [304]:
Y_pred = classifier.predict(X_test)

In [305]:
accuracy = accuracy_score(Y_pred, Y_test)

In [306]:
accuracy

0.8321678321678322

In [309]:
accuracy_train

0.8073555166374781

In [295]:
X_train.shape

(571, 7)

In [297]:
input_data = (4,1,0,35,1,0,53.1)
npinput = np.asarray(input_data)
rsdata = npinput.reshape(1, -1)
prediction = classifier.predict(rsdata)
print(prediction)

[1]

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [311]:
test = pd.read_csv('/content/test.csv')

In [312]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [338]:
test3 = test[test.isna().any(axis=1)]
test3.shape

(87, 7)

In [313]:
test = test.drop(columns='Cabin', axis = 1)
test = test.drop(columns='Name', axis = 1)
test = test.drop(columns= 'Embarked', axis = 1)
test = test.drop(columns= 'Ticket', axis = 1)
test['Fare'] = test['Fare']/513
test['Sex'].replace({'male': 1 }, inplace = True)
test['Sex'].replace({'female': 0 }, inplace = True)

In [321]:
test2 = test.dropna()

In [322]:
test2.shape

(331, 7)

In [328]:
submission = classifier.predict(test2)

In [329]:
submission

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0])

In [336]:
test3[['PassengerId']]
test3['Survived'] = 0

<ipython-input-336-a32dbd8edd35>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test3['Survived'] = 0

In [348]:
output = pd.DataFrame({'PassengerId': test2.PassengerId, 'Survived': submission})
sub = pd.concat([output,test3])
sub.to_csv('submission.csv', index=False)

In [349]:
sub

     PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch      Fare
0            892       0.0     NaN  NaN  NaN    NaN    NaN       NaN
1            893       0.0     NaN  NaN  NaN    NaN    NaN       NaN
2            894       0.0     NaN  NaN  NaN    NaN    NaN       NaN
3            895       0.0     NaN  NaN  NaN    NaN    NaN       NaN
4            896       1.0     NaN  NaN  NaN    NaN    NaN       NaN
..           ...       ...     ...  ...  ...    ...    ...       ...
408         1300       NaN     3.0  0.0  NaN    0.0    0.0  0.015050
410         1302       NaN     3.0  0.0  NaN    0.0    0.0  0.015107
413         1305       NaN     3.0  1.0  NaN    0.0    0.0  0.015692
416         1308       NaN     3.0  1.0  NaN    0.0    0.0  0.015692
417         1309       NaN     3.0  1.0  NaN    1.0    1.0  0.043583

[418 rows x 8 columns]

In [350]:
sub.to_csv('submission.csv', index=False)